# Generated by Django 4.0.6 on 2023-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link_to',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
