# Generated by Django 4.0.6 on 2023-03-04 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blog_link_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
